@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.lexakai.builders"
    
    class AssociationBuilder
    {
    }
    
    class MethodBuilder
    {
        --(constructors)--
        +MethodBuilder(LexakaiClassDiagram, TypeDeclaration<?>)
        --(collection)--
        +void addMethodDeclarations(IndentingStringBuilder)
    }
    
    class TypeBuilder
    {
        --(constructors)--
        +TypeBuilder(LexakaiClassDiagram, TypeDeclaration<?>)
        --(collection)--
        +void addTypeDeclaration(IndentingStringBuilder)
    }
    
@enduml

