@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.lexakai.indexes"
    
    class ReadMeUpdater
    {
        --(constructors)--
        +ReadMeUpdater(LexakaiProject)
        --
        +void update()
    }
    
@enduml

