@startuml

    !include ../lexakai.theme
    
    title "com.telenav.lexakai.indexes"
    
    class ReadMeIndexUpdater
    {
        --(constructors)--
        +ReadMeIndexUpdater(LexakaiProject)
        --
        +void update(Pattern javadocSectionPattern, List<Folder> childProjects, boolean addHtmlAnchors)
    }
    
@enduml

