@startuml

    !include ../lexakai/lexakai.theme

    title "com.telenav.lexakai.application.indexes"

    class ReadMeIndexUpdater
    {
        --(constructors)--
        +ReadMeIndexUpdater(LexakaiProject)
        --
        +void update(Pattern javadocSectionPattern, List<Folder> childProjects, boolean addHtmlAnchors)
    }

@enduml

