@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.lexakai.indexes"
    
    class ReadMeIndexUpdater
    {
        --(constructors)--
        +ReadMeIndexUpdater(LexakaiProject)
        --
        +void update(List<Folder> childProjects)
    }
    
@enduml

