@startuml

    !include ../lexakai.theme
    
    title "com.telenav.lexakai.annotations.associations"
    
    annotation UmlAggregation
    
    annotation UmlComposition
    
    annotation UmlRelation
    
@enduml

