@startuml

    !include ../lexakai.theme
    
    title "com.telenav.lexakai-annotations"
    
    artifact kivakit_build_metadata
    artifact com_telenav_lexakai_annotations
    com_telenav_lexakai_annotations --> kivakit_build_metadata
    
@enduml
