@startuml

    !include ../lexakai.theme
    
    title "com.telenav.lexakai-annotations"
    
    artifact com_telenav_lexakai_annotations
    artifact com_telenav_tdk_build_metadata
    com_telenav_lexakai_annotations --> com_telenav_tdk_build_metadata
    
@enduml
